---
- hosts: webservers 
  tasks: 
    - name: copy index.html onto NGINX servers
      copy:
        src: /home/ansible.jenkins/index.html
        dest: /usr/share/doc/HTML/
        owner: root
        group: root
        mode: 0755
      become: true  
